spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_store
    username: postgres
    password: postgres
  ai:
    azure:
      openai:
        endpoint: https://spring-ai-pollack.openai.azure.com/
        chat:
          options:
            deployment-name: gpt-4o
        api-key: 
