spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_store
    username: postgres
    password: postgres
  ai:
    azure:
      openai:
        api-key:
        endpoint:
        chat:
          options:
            deployment-name: